### ISSUE TITLE
[Dark Theme] Unreadable source code mode switch

### ISSUE THREAD

**Issue by ReykerBlack** [jhildenbiddle/typora-themeable#1]
![image](https://user-images.githubusercontent.com/110085062/195689121-52354c1e-da2c-4b55-aa45-4bc52b260fcc.png)

**Comment by jhildenbiddle** [comment]
Hi @ReykerBlack.

I'm not sure what I'm looking at here. What OS are you using? Where is this control located?

**Comment by ReykerBlack** [comment]
OS: Windows 10 x64
Toggle source code mode: **View -> Source Code Mode** or `Ctrl + /`
![](https://user-images.githubusercontent.com/110085062/195847144-3d50d486-ae1f-4c51-bb80-df17c36d9bf7.png)

**Comment by jhildenbiddle** [comment]
Fixed in v1.0.2.

Thanks for filing the PR, @ReykerBlack!
