### ISSUE TITLE
[Dark Theme] The tooltips of some buttons have a light theme

### ISSUE THREAD

**Issue by ReykerBlack** [jhildenbiddle/typora-themeable#10]
![0](https://user-images.githubusercontent.com/110085062/229399707-4236f004-d1f6-4aab-8321-e963cfab965f.png)

**Comment by jhildenbiddle** [comment]
This issue has been fixed and will be available in the upcoming release.

<img src="https://github.com/jhildenbiddle/typora-themeable/assets/442527/663b1da7-d395-403e-808e-fbd7f3b7d534">

Thanks, @cmeeren.

**Comment by jhildenbiddle** [comment]
v1.1.0 has been released.
