### ISSUE TITLE
Monospace text does not scale with surrounding text

### ISSUE THREAD

**Issue by dahjelle** [jhildenbiddle/typora-themeable#11]
Things work fine with Typora's default font size:

<img width="222" alt="image" src="https://github.com/jhildenbiddle/typora-themeable/assets/156557/8865673e-61ee-49a3-86be-ff01fab4888e">

But, if I change (in Typora's setting, under Appearance→Font Size) the font size to, say, 9 px, the monospace text does not seem to scale correctly:

<img width="193" alt="image" src="https://github.com/jhildenbiddle/typora-themeable/assets/156557/4ab1fd8d-a21b-429a-934f-11e0e16ec59f">

**Comment by jhildenbiddle** [comment]
This issue has been fixed and will be available in the upcoming release.

![](https://github.com/jhildenbiddle/typora-themeable/assets/442527/766721cd-5bf5-4222-a5c2-bb20c954d43e)

Thanks, @dahjelle.

**Comment by dahjelle** [comment]
Woo-hoo! Thank you! :-D

**Comment by jhildenbiddle** [comment]
v1.1.0 has been released.
