### ISSUE TITLE
Incorrect cursor/pointer when hovering over horizontal scrollbar in code fences

### ISSUE THREAD

**Issue by cmeeren** [jhildenbiddle/typora-themeable#3]
When hovering over (and using) horizontal scroll bars in code fences, the mouse pointer is still the "Text select pointer:

<img width="19" alt="image" src="https://user-images.githubusercontent.com/7766733/213871865-82350f70-ba4c-4d7c-ab57-4a235b9375c8.png">

I had expected to see the normal pointer, which is normally used for scroll bars:

<img width="28" alt="image" src="https://user-images.githubusercontent.com/7766733/213871876-97957f6b-2759-4e8a-aecb-3d6a101ea245.png">

**Comment by jhildenbiddle** [comment]
Fixed in v1.0.4.

Thanks, @cmeeren!

**Comment by cmeeren** [comment]
Thanks! Confirmed that it works.
