### ISSUE TITLE
No ligatures in level 1-3 headings (works in level 4-6 headings)

### ISSUE THREAD

**Issue by cmeeren** [jhildenbiddle/typora-themeable#5]
Here is a line with normal text and the six different headings, all containing the two characters `-` and `>`:

<img width="170" alt="image" src="https://user-images.githubusercontent.com/7766733/213909480-4ef35480-9195-4b59-9683-317c43ec5fcd.png">

As you can see, heading level 1-3 does not render the characters as a ligature. However, normal text as well as heading level 4-6 render the ligature. I suggest supporting ligatures in headings with level 1-3 too.

I assume everything is using the same font and that this fix is simple. If the reason ligatures won't show up in headings level 1-3 is that these levels use a different font, then it is indistinguishable to me from level 4-6 (I can see no differences between level 3 and 4 other than the text size), and I suggest making them use the same font so that ligatures are supported.

**Comment by jhildenbiddle** [comment]
This issue has been fixed and will be available in the upcoming release.

<img src="https://github.com/jhildenbiddle/typora-themeable/assets/442527/9dcf742d-0df7-446c-9b00-48e99b908259" width="151">

Thanks, @cmeeren.

**Comment by jhildenbiddle** [comment]
v1.1.0 has been released.
