### ISSUE TITLE
Increase visibility of scrollbars in dark mode

### ISSUE THREAD

**Issue by cmeeren** [jhildenbiddle/typora-themeable#6]
Here is a screenshot of the main scrollbar in dark mode:

<img width="109" alt="image" src="https://user-images.githubusercontent.com/7766733/213915018-04a0935c-5b0e-4f1a-9562-c8ed14639f2a.png">

In a big window, it's almost impossible to find (and I have good eyes and a good monitor).

The other scrollbars, like horizontal scrollbars in code fences, look similar, and could also benefit from increased visibility:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/7766733/213915071-b7f32166-c800-4d53-9a88-2e50cb2db678.png">

**Comment by cmeeren** [comment]
By the way, I hope you don't interpret my recent issues as complaints in any way. Themeable is the theme I'm most happy with, which is why I even bother posting these issues. 😊👍

**Comment by jhildenbiddle** [comment]
This issue has been fixed and will be available in the upcoming release.

![](https://github.com/jhildenbiddle/typora-themeable/assets/442527/04724f80-b9e2-459b-b666-8571c4710f81)

> By the way, I hope you don't interpret my recent issues as complaints in any way. Themeable is the theme I'm most happy with, which is why I even bother posting these issues.

Not at all! I appreciate you taking the time to create the issues. :)

Thanks, @cmeeren.

**Comment by jhildenbiddle** [comment]
v1.1.0 has been released.
