### ISSUE TITLE
Strikeout for nested checklist items

### ISSUE THREAD

**Issue by cmeeren** [jhildenbiddle/typora-themeable#7]
Checking a checklist item makes all of its content be striked out, including any unchecked sub-items.

![image](https://user-images.githubusercontent.com/7766733/215490076-1a5764aa-7da7-4edf-a848-fe0423b726e0.png)

I would expect unchecked sub-items to still be unchecked, so I don't mistake them for being done.

(Ideally, of course, it doesn't make that much sense to check an item without checking its sub-items, but the real world is not always ideal.)

This is not _terribly_ important to me, so don't feel bad if you drop this.

**Comment by jhildenbiddle** [comment]
This issue has been fixed and will be available in the upcoming release.

<img src="https://github.com/jhildenbiddle/typora-themeable/assets/442527/5991afbb-dd5a-433b-a751-c7dce72b9882" width="204">

Thanks, @cmeeren.

**Comment by jhildenbiddle** [comment]
v1.1.0 has been released.
