### ISSUE TITLE
Double dimming for checked sub-items

### ISSUE THREAD

**Issue by cmeeren** [jhildenbiddle/typora-themeable#8]
When nesting checkbox items, nested checked items are progressively dimmed according to their depth. I would expect all dimmed items to be the same color.

![image](https://user-images.githubusercontent.com/7766733/215490613-c3581155-34aa-4ee3-998e-506331a48452.png)

**Comment by jhildenbiddle** [comment]
This issue has been fixed and will be available in the upcoming release.

<img src="https://github.com/jhildenbiddle/typora-themeable/assets/442527/d3b0d085-639c-4120-9a4c-6ce326d0852e" width="244">

Thanks, @cmeeren.

**Comment by jhildenbiddle** [comment]
v1.1.0 has been released.
