### ISSUE TITLE
Incorrect display and cropping of text in headings

### ISSUE THREAD

**Issue by ReykerBlack** [jhildenbiddle/typora-themeable#9]
1. Highlighted headings (H1, H2) are cut off at the bottom of the text
2. Incorrect display of inline code and superscript / subscript text in headings

![Incorrect display and cropping of text in headings](https://user-images.githubusercontent.com/110085062/229396567-9a051257-b6c1-46aa-acde-cf8d21e983e2.png)

**Comment by jhildenbiddle** [comment]
This issue has been fixed and will be available in the upcoming release.

![](https://github.com/jhildenbiddle/typora-themeable/assets/442527/10dab6db-9967-4953-83e8-4c53d6ce0097)

![](https://github.com/jhildenbiddle/typora-themeable/assets/442527/47227bd0-0ba4-4881-b48f-d90f4647b8c4)

Thanks, @ReykerBlack.

**Comment by jhildenbiddle** [comment]
v1.1.0 has been released.
